//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcode_Sales
{
    using System;
    using System.Collections.Generic;
    
    public partial class AqtaProducts
    {
        public int Id { get; set; }
        public Nullable<int> WarehousesID { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string ProductName { get; set; }
        public string Barcode { get; set; }
        public Nullable<double> PurchasePrice { get; set; }
        public Nullable<double> SalePrice { get; set; }
        public string Unit { get; set; }
        public string Tax { get; set; }
        public string Ingredients { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<int> RetentionPeriod { get; set; }
        public string StorageConditions { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> ShowPosScreen { get; set; }
        public Nullable<bool> AmountNotification { get; set; }
        public Nullable<bool> EndDateNotification { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> IsDeleted { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Warehouses Warehouses { get; set; }
    }
}
