//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcode_Sales
{
    using System;
    using System.Collections.Generic;
    
    public partial class CloseShiftReport
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> OpenShiftDate { get; set; }
        public Nullable<System.DateTime> CloseShiftDate { get; set; }
        public string FiskalID { get; set; }
        public string JsonResponse { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
