//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcode_Sales
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.CustomersDebts = new HashSet<CustomersDebt>();
            this.SalesDatas = new HashSet<SalesData>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public string NameSurname { get; set; }
        public string CompanyName { get; set; }
        public Nullable<System.DateTime> DateBirth { get; set; }
        public string Gender { get; set; }
        public string Phone { get; set; }
        public string Voen { get; set; }
        public Nullable<double> Debt { get; set; }
        public Nullable<double> Balance { get; set; }
        public string BankName { get; set; }
        public string BankVoen { get; set; }
        public string BankAccountNumber { get; set; }
        public string BankKOD { get; set; }
        public string BankSwift { get; set; }
        public string Email { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CustomerGroupId { get; set; }
    
        public virtual CustomerGroup CustomerGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomersDebt> CustomersDebts { get; set; }
        public virtual Users User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesData> SalesDatas { get; set; }
    }
}
