//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcode_Sales
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceRollback
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvoiceRollback()
        {
            this.InvoiceRollbackDetails = new HashSet<InvoiceRollbackDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public Nullable<System.DateTime> RollbackDate { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public Nullable<double> TotalPurchasePrice { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public string Commnet { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceRollbackDetail> InvoiceRollbackDetails { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual Warehouses Warehouse { get; set; }
        public virtual Users Users { get; set; }
    }
}
