//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcode_Sales
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceProducts
    {
        public int Id { get; set; }
        public Nullable<int> InvoiceInfoId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> PurchasePrice { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> TotalPurchasePrice { get; set; }
    
        public virtual InvoiceInfo InvoiceInfo { get; set; }
        public virtual Products Products { get; set; }
    }
}
