//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcode_Sales
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NextposDBEntities : DbContext
    {
        public NextposDBEntities()
            : base("name=NextposDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Colors> Colors { get; set; }
        public virtual DbSet<Logs> Logs { get; set; }
        public virtual DbSet<Sizes> Sizes { get; set; }
        public virtual DbSet<Warehouses> Warehouses { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<AqtaProducts> AqtaProducts { get; set; }
        public virtual DbSet<SupplierPayment> SupplierPayments { get; set; }
        public virtual DbSet<SuppliersDebt> SuppliersDebts { get; set; }
        public virtual DbSet<CustomerPayment> CustomerPayments { get; set; }
        public virtual DbSet<CustomersDebt> CustomersDebts { get; set; }
        public virtual DbSet<SalesData> SalesDatas { get; set; }
        public virtual DbSet<TerminalIncomesAndExpens> TerminalIncomesAndExpenses { get; set; }
        public virtual DbSet<CloseShiftReport> CloseShiftReports { get; set; }
        public virtual DbSet<ReturnPos> ReturnPos { get; set; }
        public virtual DbSet<ReturnPosDetail> ReturnPosDetails { get; set; }
        public virtual DbSet<TaxType> TaxTypes { get; set; }
        public virtual DbSet<PaymentType> PaymentTypes { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<UnitType> UnitTypes { get; set; }
        public virtual DbSet<InvoiceDetail> InvoiceDetails { get; set; }
        public virtual DbSet<SalesDataDetail> SalesDataDetail { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<InvoiceRollbackDetail> InvoiceRollbackDetails { get; set; }
        public virtual DbSet<InvoiceRollback> InvoiceRollbacks { get; set; }
        public virtual DbSet<view_InvoiceRollbackList> view_InvoiceRollbackList { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<Terminals> Terminals { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<CustomerGroup> CustomerGroups { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
    }
}
