//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcode_Sales
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosBasket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PosBasket()
        {
            this.PosBasketItems = new HashSet<PosBasketItem>();
        }
    
        public int Id { get; set; }
        public string BasketName { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public System.DateTime CreatedDatetime { get; set; }
        public int CreatedUserId { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PosBasketItem> PosBasketItems { get; set; }
        public virtual User User { get; set; }
    }
}
