//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcode_Sales
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosSale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PosSale()
        {
            this.PosSaleItems = new HashSet<PosSaleItem>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public System.DateTime SaleDate { get; set; }
        public System.DateTime SaleDatetime { get; set; }
        public string ReceiptNo { get; set; }
        public string LongFiscalId { get; set; }
        public string ShortFiscalId { get; set; }
        public string Rrn { get; set; }
        public decimal Total { get; set; }
        public decimal Cash { get; set; }
        public decimal Card { get; set; }
        public decimal IncomingSum { get; set; }
        public decimal Residue { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string Note { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PosSaleItem> PosSaleItems { get; set; }
        public virtual User User { get; set; }
    }
}
