//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcode_Sales
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.InvoiceDetails = new HashSet<InvoiceDetail>();
            this.SalesDataDetail = new HashSet<SalesDataDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<byte> Type { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string ProductName { get; set; }
        public string ProductCode { get; set; }
        public string Barcode { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> PurchasePrice { get; set; }
        public Nullable<double> SalePrice { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> TaxId { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public int CreatedUserId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Categories Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        public virtual TaxType TaxTypes { get; set; }
        public virtual UnitType UnitTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesDataDetail> SalesDataDetail { get; set; }
        public virtual Users Users { get; set; }
    }
}
