//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcode_Sales
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.InvoiceProducts = new HashSet<InvoiceProducts>();
            this.SalesDataDetails = new HashSet<SalesDataDetail>();
        }
    
        public int Id { get; set; }
        public string Type { get; set; }
        public Nullable<int> WarehousesID { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string ProductName { get; set; }
        public string ProductCode { get; set; }
        public string Barcode { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> PurchasePrice { get; set; }
        public Nullable<double> SalePrice { get; set; }
        public string Unit { get; set; }
        public string Tax { get; set; }
        public Nullable<int> ColorID { get; set; }
        public Nullable<int> SizeID { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> FinisDate { get; set; }
        public byte[] Image { get; set; }
        public Nullable<bool> ShowPosScreen { get; set; }
        public Nullable<bool> AmountNotification { get; set; }
        public Nullable<bool> EndDateNotification { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> IsDeleted { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Colors Colors { get; set; }
        public virtual Sizes Sizes { get; set; }
        public virtual Stores Stores { get; set; }
        public virtual Warehouses Warehouses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceProducts> InvoiceProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesDataDetail> SalesDataDetails { get; set; }
    }
}
