//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcode_Sales
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnPos
    {
        public int Id { get; set; }
        public Nullable<int> SaleDataId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string ReceiptNo { get; set; }
        public string LongFiscalId { get; set; }
        public string ShortFiscalId { get; set; }
        public string Rrn { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<System.DateTime> ReturnDatetime { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Cash { get; set; }
        public Nullable<decimal> Card { get; set; }
        public Nullable<decimal> IncomingSum { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string Note { get; set; }
    }
}
