//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcode_Sales
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Role()
        {
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public bool IsDeleted { get; set; }
        public string RoleName { get; set; }
        public bool PosSales { get; set; }
        public bool PosReturn { get; set; }
        public bool Bank { get; set; }
        public bool Reports { get; set; }
        public bool Settings { get; set; }
        public bool User { get; set; }
        public bool Credit { get; set; }
        public bool MoneyBox { get; set; }
        public bool Admin { get; set; }
        public bool Cashier { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
