//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcode_Sales
{
    using System;
    using System.Collections.Generic;

    public partial class SalesDataDetail
    {
        public int Id { get; set; }
        public Nullable<int> SaleDataId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> SalePrice { get; set; }
        public Nullable<double> Discount { get; set; }
        public double Total
        {
            get
            {
               double result = (double)(SalePrice * Quantity);
                return result;
            }
        }
        public virtual Products Product { get; set; }
        public virtual SalesData SalesData { get; set; }
    }
}
