//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcode_Sales
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scale
    {
        public int Id { get; set; }
        public int StoreId { get; set; }
        public string ModelName { get; set; }
        public string IpAddress { get; set; }
        public string FilePath { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedUserId { get; set; }
    
        public virtual Store Store { get; set; }
        public virtual User User { get; set; }
    }
}
