//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcode_Sales
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierPayment
    {
        public int Id { get; set; }
        public Nullable<int> SupplierDebtId { get; set; }
        public Nullable<double> DebtPaid { get; set; }
        public Nullable<double> TaxPaid { get; set; }
        public string Comment { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public string PaymentType { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
    
        public virtual SuppliersDebt SuppliersDebt { get; set; }
    }
}
