//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcode_Sales
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suppliers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Suppliers()
        {
            this.SuppliersDebts = new HashSet<SuppliersDebt>();
            this.Products = new HashSet<Products>();
        }
    
        public int Id { get; set; }
        public string SupplierName { get; set; }
        public string Voen { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<double> Debt { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public string BankName { get; set; }
        public string BankVoen { get; set; }
        public string BankAccountNumber { get; set; }
        public string BankKOD { get; set; }
        public string BankSwift { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuppliersDebt> SuppliersDebts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products> Products { get; set; }
    }
}
