//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcode_Sales
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierPayment
    {
        public int Id { get; set; }
        public int SupplierDebtId { get; set; }
        public decimal DebtPaid { get; set; }
        public decimal TaxPaid { get; set; }
        public string Comment { get; set; }
        public bool IsDeleted { get; set; }
        public int PaymentTypeId { get; set; }
        public System.DateTime PayDate { get; set; }
        public System.DateTime LogDate { get; set; }
    
        public virtual PaymentType PaymentType { get; set; }
        public virtual SuppliersDebt SuppliersDebt { get; set; }
    }
}
