//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcode_Sales
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terminal
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string IpAddress { get; set; }
        public string MerchantId { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Store Store { get; set; }
        public virtual User User { get; set; }
    }
}
