//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcode_Sales
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_InvoiceRollbackList
    {
        public int WarehouseId { get; set; }
        public string WarehouseName { get; set; }
        public int InvoiceId { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string SupplierName { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string ProductName { get; set; }
        public string Barcode { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> PurchasePrice { get; set; }
    }
}
